parameters:
#    acme_entreprise.example.class: Acme\EntrepriseBundle\Example

services:
#    acme_entreprise.example:
#        class: %acme_entreprise.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
