parameters:
#    acme_entreprise.example.class: Acme\EntrepriseBundle\Example

services:
#    acme_entreprise.example:
#        class: %acme_entreprise.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    acme_entreprise.admin.entreprise:
        class: Acme\EntrepriseBundle\Admin\EntrepriseAdmin
        arguments: [~, Acme\EntrepriseBundle\Entity\Entreprise, AcmeEntrepriseBundle:EntrepriseAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Entreprise}
